spring:
  application:
    name: myweb

  thymeleaf:
    check-template-location: true
    mode: HTML
    prefix: classpath:templates/
    suffix: .html
    view-names: th/*
    cache: false

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: 8088
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true